### ISSUE TITLE
action states: inProgress, pending, notInterested, doing, done, abandoned, na 

### ISSUE THREAD

**Issue by yilinh** [CIVIS-project/YouPower#59]
inProgress: the actions a user is currently taking
pending: the actions that are scheduled, 
notInterested: the actions users don't like to do
doing: the actions a user has been already doing before the action is suggested to a user 
done: the actions completed by a user through our suggestions
abandoned: the actions a user first accepted then abandoned afterwards
na: the actions not applicable to a user

**Comment by FruitieX** [comment]
Currently we have:
- `pending` - user has postponed action
- `inProgress` - user is performing action
- `done` - user is done performing action
- `declined` - user is not interested in the action for some reason
- `na` - not applicable actions

Furthermore if an action is abandoned (after accepting), it is put into `declined` but the action object will have a `wasCanceled` field which is set to true.

If the user is already doing an action it is put into `done` but the action object will have a `alreadyDoing` field set to true.

My idea here was to group the many states a little bit, so that states with mostly the same outcome (e.g. we wouldn't suggest neither `done` or `alreadyDoing` actions to the user again, and both should count toward the user's total leaf count) are grouped together, just with a flag set so we can separate them if needed. This way code that e.g. checks how many leafs you have only needs to check the `done` state. By this logic the grouping might need some re-thinking however.

Or maybe we should just separate them all for the sake of clarity?

**Comment by yilinh** [comment]
bot are fine. It just need to be documented! ;)

**Comment by yesgee** [comment]
Need to figure out how to calculate leaves for done actions

**Comment by yilinh** [comment]
Can we do it simple, e.g., effort + impact ?

**Comment by FruitieX** [comment]
Or maybe something like impact multiplied by 20, since if I recall correctly both effort & impact are rated 1-5 so this would mean an action can be either 20, 40, 60, 80 or 100 leaves worth.

**Comment by yilinh** [comment]
the number can become big then. hey we need to first agree upon: 
(1) are the points for each action set by front end or back end? 
(2) are the calculation of the points of each user done by front end or back end? 
(3) do we need to separate points for actions and "points" for giving comments/feedback? and are there anything else where users can get points? (e.g. first participant of an action...)

**Comment by FruitieX** [comment]
1 & 2: I would say on the back-end. Otherwise to know another user's points on the front-end, you would need a complete list of all of _their_ user actions as well.

3: I would separate them in the back-end, but whenever we report a total leaf count to the front-end, they are combined. For instance (in the back-end only, "invisible" to the front-end) we would just have an incrementing counter of how many times a user has sent feedback, which is separate from the list of actions the user has completed.
